branches:
  only:
  - pelican
language: python
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - secure: NpiMvH1FmEw9UVoODB6x31XgSmR+tmZcIkKz+7BdmC2zBKsxXGmthlfHnh7fFLeZ1tIJ9g0lA9BUPbWUbLxunQLQ31gL5ATaGoAeqlc+FZJuctIiL+JudTftVxwTAaiv3PdrNlirHd8kOMReRAb33reMg2pFt8R6feSb1zLZsr4=
before_install:
- git submodule update --init --recursive
after_success: bash deploy.sh
